name1 = String.new('egoing')
name2 = String.new('dgboy')
puts(name1.reverse())
puts(name2.reverse())
puts(name1.upcase())
puts(name1.size())
names = Array.new()
names.push('egoing')
names.push('dgboy')
puts(names)
puts(names.join(', '))
